In [1]:
print("hello world")

hello world


# biaoti

In [10]:
import numpy as np
arr1 = np.array([6,2,-7,2,8,-2,1])
print(arr1)
# arr = np.array([[1,2,3],[4,5,6]])
# arr

[ 6  2 -7  2  8 -2  1]


In [9]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
print(arr1.ndim)
# 维度 ，形状 ， 大小 ， 类型
print(arr.ndim)
print(arr1.shape)
print(arr.shape)
print(arr1.size)
print(arr.size)
print(arr1.dtype)
print(arr.dtype)

1
2
(7,)
(2, 3)
7
6
int64
int64


In [16]:
# 全是0的数组
arr3 = np.zeros(6)
arr3

array([0., 0., 0., 0., 0., 0.])

In [17]:
# 全是1的数组
arr4 = np.ones(6)
arr4

array([1., 1., 1., 1., 1., 1.])

In [18]:
# 创造一个10~20的偶数的数组
arr5 = np.arange(10,21,2)
arr5

array([10, 12, 14, 16, 18, 20])

In [20]:
arr6 = np.array([1,3,2,4,9])
arr7 = np.ones(5)
arr8 = np.zeros(3)

In [24]:
arr9 = np.concatenate([arr6,arr7,arr8])
arr9

array([1., 3., 2., 4., 9., 1., 1., 1., 1., 1., 0., 0., 0.])

In [25]:
arr6.sort()
arr6

array([1, 2, 3, 4, 9])

In [30]:
print(arr6[2])

3


In [31]:
print(arr6[1:4])

[2 3 4]


In [32]:
arr10 = arr6 + arr7
arr10

array([ 2.,  3.,  4.,  5., 10.])

In [33]:
print(arr6 * (-5))

[ -5 -10 -15 -20 -45]


In [35]:
print(arr6.max())
print(arr6.min())
print(arr6.sum())
print(arr6.mean())

9
1
19
3.8


In [37]:
print(arr6[(arr6<1) | (arr6>3)])

[4 9]
